@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NTIyMDgwNDF9.FvM6krhGokSmApVUjbwgN1QDBzlPL_Trx77hciqaO5g

### Drug Index
GET http://localhost:3000/drugs.json

### Drug Show
GET http://localhost:3000/drugs/1.json

### Drug Post
POST http://localhost:3000/drugs.json
Content-Type: application/json

{
  "name": "create name jb test",
  "description": "create description jb test",
  "classification_id": 1,
  "image_url": "create image_url jb test"
}

### Drug Patch
PATCH http://localhost:3000/drugs/5.json
Content-Type: application/json

{
  "class_id": 2
}

### Drug Delete
DELETE http://localhost:3000/drugs/3.json
  
### ### ### ### ### ### ### ### ### ### ###
###                                     ###
### ###                             ### ###
### ### ###                     ### ### ###
### ### ### ###             ### ### ### ###
### ### ### ### ###     ### ### ### ### ###
### ### ### ### ### ### ### ### ### ### ###
### ### ### ### ###     ### ### ### ### ###
### ### ### ###             ### ### ### ###
### ### ###                     ### ### ###
### ###                             ### ###
###                                     ###
### ### ### ### ### ### ### ### ### ### ###

### Classification Index
GET http://localhost:3000/classifications.json

### Classification Show
GET http://localhost:3000/classifications/1.json

### Classification Post
POST http://localhost:3000/classifications.json
Content-Type: application/json

{
  "name": "jb test",
  "description": "jb description"
}

### Classification Patch
PATCH http://localhost:3000/classifications/1.json
Content-Type: application/json

{
  "description": "TEST WORKED"
}

### ### ### ### ### ### ### ### ### ### ###
###                                     ###
### ###                             ### ###
### ### ###                     ### ### ###
### ### ### ###             ### ### ### ###
### ### ### ### ###     ### ### ### ### ###
### ### ### ### ### ### ### ### ### ### ###
### ### ### ### ###     ### ### ### ### ###
### ### ### ###             ### ### ### ###
### ### ###                     ### ### ###
### ###                             ### ###
###                                     ###
### ### ### ### ### ### ### ### ### ### ###

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Victoria",
  "email": "victoria@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "victoria@test.com",
  "password": "password"
}

### ### ### ### ### ### ### ### ### ### ###
###                                     ###
### ###                             ### ###
### ### ###                     ### ### ###
### ### ### ###             ### ### ### ###
### ### ### ### ###     ### ### ### ### ###
### ### ### ### ### ### ### ### ### ### ###
### ### ### ### ###     ### ### ### ### ###
### ### ### ###             ### ### ### ###
### ### ###                     ### ### ###
### ###                             ### ###
###                                     ###
### ### ### ### ### ### ### ### ### ### ###

### DrugUser index
GET http://localhost:3000/drug_users.json
Authorization: Bearer {{jwt}}