# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
# Classification.create(name: "Anti-Depressant")
# Classification.create(name: "Anti-Inflammatory")
# Classification.create(name: "Antibiotics")
Drug.create(name: "Hydrocodone-APAP", description: "Hydrocodone and acetaminophen combination is used to relieve pain severe enough to require opioid treatment and when other pain medicines did not work well enough or cannot be tolerated.

  Acetaminophen is used to relieve pain and reduce fever in patients. It does not become habit-forming when taken for a long time. But acetaminophen may cause other unwanted effects when taken in large doses, including liver damage.
  
  Hydrocodone belongs to the group of medicines called narcotic analgesics (pain medicines). It acts on the central nervous system (CNS) to relieve pain, and stops or prevents cough.", classification_id: 1, image_url: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.webmd.com%2Fdrugs%2F2%2Fdrug-251%2Fhydrocodone-acetaminophen-oral%2Fdetails&psig=AOvVaw30kD-7HAmLjF756oL3E8R0&ust=1654032177668000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCMCTipeUiPgCFQAAAAAdAAAAABAD")
Drug.create(name: "Fluoxetine", description: "Fluoxetine is used to treat depression, obsessive-compulsive disorder (OCD), bulimia nervosa, premenstrual dysphoric disorder (PMDD), and panic disorder. It is also used together with olanzapine to treat depression that is part of bipolar disorder and treatment resistant depression in patients who have received at least 2 previous treatments but did not work well.", classification_id: 6, image_url: "https://www.drugs.com/images/pills/nlm/50111064801.jpg")
Drug.create(name: "Ibuprofen", description: "Ibuprofen is used to reduce fever and treat pain or inflammation caused by many conditions such as headache, toothache, back pain, arthritis, menstrual cramps, or minor injury. ", classification_id: 7, image_url: "https://www.cvs.com/webcontent/images/drug/DrugItem_22468.JPG")
Drug.create(name: "Oxycodone", description: "Oxycodone is used to relieve moderate to severe pain. Oxycodone extended-release tablets and extended-release capsules are used to relieve severe pain in people who are expected to need pain medication around the clock for a long time and who cannot be treated with other medications. Oxycodone extended-release tablets and extended-release capsules should not be used to treat pain that can be controlled by medication that is taken as needed. Oxycodone extended-release tablets, extended-release capsules, and concentrated solution should only be used to treat people who are tolerant (used to the effects of the medication) to opioid medications because they have taken this type of medication for at least one week. Oxycodone is in a class of medications called opiate (narcotic) analgesics. It works by changing the way the brain and nervous system respond to pain.", classification_id: 1, image_url: "https://www.cvs.com/webcontent/images/drug/DrugItem_11524.JPG")
Drug.create(name: "Naproxen", description: "Naproxen is used to relieve pain, tenderness, swelling, and stiffness caused by osteoarthritis (arthritis caused by a breakdown of the lining of the joints), rheumatoid arthritis (arthritis caused by swelling of the lining of the joints), juvenile arthritis (a form of joint disease in children), and ankylosing spondylitis (arthritis that mainly affects the spine). Prescription naproxen tablets, extended-release tablets, and suspension are also used to relieve shoulder pain caused by bursitis (inflammation of a fluid-filled sac in the shoulder joint), tendinitis (inflammation of the tissue that connects muscle to bone), gouty arthritis (attacks of joint pain caused by a build-up of certain substances in the joints), and pain from other causes, including menstrual pain (pain that happens before or during a menstrual period). Nonprescription naproxen is used to reduce fever and to relieve mild pain from headaches, muscle aches, arthritis, menstrual periods, the common cold, toothaches, and backaches. Naproxen is in a class of medications called NSAIDs. It works by stopping the body's production of a substance that causes pain, fever, and inflammation.", classification_id: 7, image_url: "https://www.grxstatic.com/d4fuqqd5l3dbz/products/DrugItem_21564.JPG")
Drug.create(name: "Amoxicillin", description: "Amoxicillin is used to treat certain infections caused by bacteria, such as pneumonia; bronchitis (infection of the airway tubes leading to the lungs); and infections of the ears, nose, throat, urinary tract, and skin. It is also used in combination with other medications to eliminate H. pylori, a bacteria that causes ulcers. Amoxicillin is in a class of medications called penicillin-like antibiotics. It works by stopping the growth of bacteria.", classification_id: 8, image_url: "https://www.grxstatic.com/d4fuqqd5l3dbz/products/DrugItem_10708.JPG")
Drug.create(name: "Cephalexin", description: "Cephalexin is used to treat certain infections caused by bacteria such as pneumonia and other respiratory tract infections; and infections of the bone, skin, ears, , genital, and urinary tract. Cephalexin is in a class of medications called cephalosporin antibiotics. It works by killing bacteria.", classification_id: 8, image_url: "https://www.grxstatic.com/d4fuqqd5l3dbz/products/DrugItem_11556.JPG")
Drug.create(name: "Citalopram", description: "Citalopram is used to treat depression, including major depressive disorder (MDD). It is an antidepressant that belongs to a group of medicines known as selective serotonin reuptake inhibitors (SSRIs). These medicines are thought to work by increasing the activity of a chemical called serotonin in the brain.", classification_id: 6, image_url: "https://www.grxstatic.com/d4fuqqd5l3dbz/products/DrugItem_14177.JPG")
Drug.create(name: "Methadone", description: "Methadone changes the way your brain and nervous system respond to pain so that you feel relief. Its effects are slower than those of other strong painkillers like morphine. Your doctor may prescribe methadone if you’re in a lot of pain from an injury, surgery, or long-term illness.", classification_id: 1, image_url: "https://www.drugs.com/images/pills/nlm/000544571.jpg")
Drug.create(name: "Cefadroxil", description: "Cefadroxil is used to treat certain infections caused by bacteria such as infections of the skin, throat, tonsils, and urinary tract. Cefadroxil is in a class of medications called cephalosporin antibiotics. It works by killing bacteria.", classification_id: 8, image_url: "https://www.grxstatic.com/d4fuqqd5l3dbz/products/DrugItem_11883.JPG")